import path from 'path';
import chalk from 'chalk';
import { loadDeployConfig, hasDeployConfig, saveDeployConfig } from '../../lib/deploy-config.js';
import { createDeploymentZip } from '../../lib/zip.js';
import { HostingAPI, UpsertServerPayload } from '../../lib/hosting.js';
import { createSpinner } from '../../lib/spinner.js';
import { logger } from '../../lib/logger.js';
import { autoConfigWithPreview } from '../../lib/auto-config.js';
import { confirm } from '../../lib/prompts.js';
import { DeployConfig } from '../../types.js';

export interface DeployCommandOptions {
  config?: string;
  path?: string;
  project?: string;
  start?: boolean;
}

async function resolveProject(hosting: HostingAPI, selector: string | undefined, fallbackName: string) {
  const projects = await hosting.listProjects();
  const requested = selector?.trim();
  const matches = projects.filter((project) =>
    requested
      ? [project.id, project.slug, project.name].includes(requested)
      : project.name === fallbackName
  );

  if (matches.length > 1) {
    throw new Error(`Multiple projects match "${requested ?? fallbackName}". Pass --project with an exact project ID.`);
  }
  if (matches[0]) return matches[0];
  if (requested) {
    throw new Error(`Project "${requested}" was not found.`);
  }

  logger.info(`Creating project ${fallbackName}`);
  return hosting.createProject(fallbackName);
}

export async function deploy(options: DeployCommandOptions) {
  const projectRoot = path.resolve(options.path ?? process.cwd());
  const hosting = new HostingAPI();

  let deployConfig: DeployConfig;
  let wasAutoGenerated = false;

  // Check if deploy config exists
  if (hasDeployConfig(projectRoot, options.config)) {
    deployConfig = loadDeployConfig(projectRoot, options.config);
  } else {
    // No config - run auto-detection with preview
    logger.info('No autodisc.yml found - analyzing your project...\n');
    const autoConfig = await autoConfigWithPreview(projectRoot);
    if (!autoConfig) {
      return; // User cancelled or detection failed
    }
    deployConfig = autoConfig;
    wasAutoGenerated = true;
  }

  let uploadKey: string | undefined;
  let uploadName: string | undefined;
  let zipCleanup: (() => void) | undefined;

  if (deployConfig.source.type === 'upload') {
    const packageSpinner = createSpinner('Packaging project directory');
    packageSpinner.start();
    try {
      const zip = await createDeploymentZip({ projectRoot, ignore: deployConfig.ignore });
      packageSpinner.succeed();
      zipCleanup = zip.cleanup;
      const uploadSpinner = createSpinner('Uploading deployment bundle');
      uploadSpinner.start();
      try {
        const result = await hosting.uploadBundle(zip.path);
        uploadSpinner.succeed();
        uploadKey = result.upload_key;
        uploadName = path.basename(zip.path);
        logger.info(`Uploaded bundle (${(result.size_bytes / (1024 * 1024)).toFixed(2)} MB)`);
      } catch (error) {
        uploadSpinner.fail();
        throw error;
      }
    } catch (error) {
      packageSpinner.fail();
      zipCleanup?.();
      throw error;
    } finally {
      zipCleanup?.();
    }
  }

  if (deployConfig.source.type === 'repo' && !deployConfig.source.repo_full_name) {
    throw new Error('source.repo_full_name is required for repo deployments');
  }

  const publicPort = deployConfig.runtime.port;
  const isPublic = publicPort !== undefined && deployConfig.deployment.public !== false;
  const setupCommand = deployConfig.runtime.build_steps?.filter(Boolean).join(' && ') || undefined;

  const payload: UpsertServerPayload = {
    name: deployConfig.name,
    source_type: deployConfig.source.type,
    repo_full_name: deployConfig.source.repo_full_name,
    repo_branch: deployConfig.source.repo_branch,
    source_upload_key: uploadKey,
    source_upload_name: uploadName,
    start_command: deployConfig.runtime.start_command,
    setup_command: setupCommand,
    plan_type: deployConfig.deployment.plan_type,
    environment: deployConfig.environment ?? {},
    auto_restart: deployConfig.deployment.auto_restart ?? true,
    service_type: 'app',
    port: publicPort,
    internal: deployConfig.deployment.public === false,
  };

  const project = await resolveProject(hosting, options.project, deployConfig.name);
  const hydratedProject = await hosting.getProject(project.id);
  let server = hydratedProject.services.find((service) => service.name === deployConfig.name);
  const serviceAlreadyExisted = Boolean(server);

  if (!server) {
    const upsertSpinner = createSpinner('Creating project service');
    upsertSpinner.start();
    try {
      server = await hosting.addProjectService(
        project.id,
        payload,
        hydratedProject.default_environment_id,
      );
      upsertSpinner.succeed();
    } catch (error) {
      upsertSpinner.fail();
      throw error;
    }
  }

  const cliConfig = (await import('../../lib/config.js')).getConfigManager();
  cliConfig.setValue('deploy.currentProject', project.id);
  cliConfig.setValue('deploy.currentServer', server.id);

  if (serviceAlreadyExisted) {
    server = await hosting.updateServer(server.id, {
      name: deployConfig.name,
      ...(deployConfig.source.type === 'repo'
        ? {
            source_type: 'repo' as const,
            repo_full_name: deployConfig.source.repo_full_name,
            repo_branch: deployConfig.source.repo_branch,
          }
        : {}),
      start_command: deployConfig.runtime.start_command,
      setup_command: setupCommand,
      detected_stack: deployConfig.runtime.stack,
      port: publicPort,
      internal: deployConfig.deployment.public === false,
      show_url: isPublic,
      environment: deployConfig.environment
        ? { ...(server.environment ?? {}), ...deployConfig.environment }
        : undefined,
      auto_restart: deployConfig.deployment.auto_restart ?? true,
    });
  }

  if (deployConfig.source.type === 'upload' && uploadKey) {
    const deploySpinner = createSpinner(options.start === false ? 'Applying deployment bundle' : 'Deploying project');
    deploySpinner.start();
    try {
      server = await hosting.deployBundle(server.id, {
        upload_key: uploadKey,
        upload_name: uploadName,
        start_command: deployConfig.runtime.start_command,
        setup_command: setupCommand,
        detected_stack: deployConfig.runtime.stack,
        environment: deployConfig.environment
          ? { ...(server.environment ?? {}), ...deployConfig.environment }
          : undefined,
        auto_restart: deployConfig.deployment.auto_restart ?? true,
        start: options.start !== false,
      });
      deploySpinner.succeed();
    } catch (error) {
      deploySpinner.fail();
      throw error;
    }
  }

  if (options.start === false) {
    logger.success('Hosting server updated. Skipping start (--no-start).');
    // Still offer to save config if auto-generated
    if (wasAutoGenerated) {
      console.log('');
      const shouldSave = await confirm('Save this configuration for future deploys?', true);
      if (shouldSave) {
        saveDeployConfig(projectRoot, deployConfig);
      }
    }
    return;
  }

  const startSpinner = createSpinner('Deploying project');
  if (deployConfig.source.type === 'repo') {
    startSpinner.start();
    try {
      server = serviceAlreadyExisted
        ? await hosting.redeployServer(server.id)
        : await hosting.startServer(server.id);
      startSpinner.succeed();
    } catch (error) {
      startSpinner.fail();
      throw error;
    }
  }
  logger.success(`Deployment started: ${server.name} (${chalk.cyan(server.status ?? 'queued')})`);

  // Offer to save auto-generated config for future deploys
  if (wasAutoGenerated) {
    console.log('');
    const shouldSave = await confirm('Save this configuration for future deploys?', true);
    if (shouldSave) {
      saveDeployConfig(projectRoot, deployConfig);
    }
  }
}
