import path from 'path';
import chalk from 'chalk';
import { loadDeployConfig, hasDeployConfig, saveDeployConfig } from '../../lib/deploy-config.js';
import { createDeploymentZip } from '../../lib/zip.js';
import { HostingAPI, UpsertServerPayload } from '../../lib/hosting.js';
import { createSpinner } from '../../lib/spinner.js';
import { logger } from '../../lib/logger.js';
import { autoConfigWithPreview } from '../../lib/auto-config.js';
import { confirm } from '../../lib/prompts.js';
import { DeployConfig } from '../../types.js';

export interface DeployCommandOptions {
  config?: string;
  path?: string;
  start?: boolean;
}

export async function deploy(options: DeployCommandOptions) {
  const projectRoot = path.resolve(options.path ?? process.cwd());
  const hosting = new HostingAPI();

  let deployConfig: DeployConfig;
  let wasAutoGenerated = false;

  // Check if deploy config exists
  if (hasDeployConfig(projectRoot, options.config)) {
    deployConfig = loadDeployConfig(projectRoot, options.config);
  } else {
    // No config - run auto-detection with preview
    logger.info('No autodisc.yml found - analyzing your project...\n');
    const autoConfig = await autoConfigWithPreview(projectRoot);
    if (!autoConfig) {
      return; // User cancelled or detection failed
    }
    deployConfig = autoConfig;
    wasAutoGenerated = true;
  }

  let uploadKey: string | undefined;
  let uploadName: string | undefined;
  let zipCleanup: (() => void) | undefined;

  if (deployConfig.source.type === 'upload') {
    const packageSpinner = createSpinner('Packaging project directory');
    packageSpinner.start();
    try {
      const zip = await createDeploymentZip({ projectRoot, ignore: deployConfig.ignore });
      packageSpinner.succeed();
      zipCleanup = zip.cleanup;
      const uploadSpinner = createSpinner('Uploading deployment bundle');
      uploadSpinner.start();
      try {
        const result = await hosting.uploadBundle(zip.path);
        uploadSpinner.succeed();
        uploadKey = result.upload_key;
        uploadName = path.basename(zip.path);
        logger.info(`Uploaded bundle (${(result.size_bytes / (1024 * 1024)).toFixed(2)} MB)`);
      } catch (error) {
        uploadSpinner.fail();
        throw error;
      }
    } catch (error) {
      packageSpinner.fail();
      zipCleanup?.();
      throw error;
    } finally {
      zipCleanup?.();
    }
  }

  if (deployConfig.source.type === 'repo' && !deployConfig.source.repo_full_name) {
    throw new Error('source.repo_full_name is required for repo deployments');
  }

  const payload: UpsertServerPayload = {
    name: deployConfig.name,
    source_type: deployConfig.source.type,
    repo_full_name: deployConfig.source.repo_full_name,
    repo_branch: deployConfig.source.repo_branch,
    source_upload_key: uploadKey,
    source_upload_name: uploadName,
    start_command: deployConfig.runtime.start_command,
    plan_type: deployConfig.deployment.plan_type,
    environment: deployConfig.environment ?? {},
    auto_restart: deployConfig.deployment.auto_restart ?? true,
  };

  const upsertSpinner = createSpinner('Creating hosting server');
  upsertSpinner.start();
  try {
    await hosting.upsertServer(payload);
    upsertSpinner.succeed();
  } catch (error) {
    upsertSpinner.fail();
    throw error;
  }

  if (options.start === false) {
    logger.success('Hosting server updated. Skipping start (--no-start).');
    // Still offer to save config if auto-generated
    if (wasAutoGenerated) {
      console.log('');
      const shouldSave = await confirm('Save this configuration for future deploys?', true);
      if (shouldSave) {
        saveDeployConfig(projectRoot, deployConfig);
      }
    }
    return;
  }

  const startSpinner = createSpinner('Starting hosting server');
  startSpinner.start();
  try {
    const server = await hosting.startServer();
    startSpinner.succeed();
    logger.success(`Deployment started: ${server.name} (${chalk.cyan(server.status)})`);
  } catch (error) {
    startSpinner.fail();
    throw error;
  }

  // Offer to save auto-generated config for future deploys
  if (wasAutoGenerated) {
    console.log('');
    const shouldSave = await confirm('Save this configuration for future deploys?', true);
    if (shouldSave) {
      saveDeployConfig(projectRoot, deployConfig);
    }
  }
}
